name       : libbytesize
version    : '0.11'
release    : 1
source     :
    - https://github.com/storaged-project/libbytesize/archive/0.11.tar.gz : 3eff9a4b3350420b5e1ecfff523a739049d000b34485e3e1ccf4a4d7685490cb
license    : LGPL-2.1
component  : programming.library
summary    : A tiny library providing a C "class" for working with arbitrary big sizes in bytes
description: |
    The libbytesize is a C library that facilitates work with sizes in
    bytes. Be it parsing the input from users or producing a nice human readable
    representation of a size in bytes this library takes localization into
    account. It also provides support for sizes bigger than MAXUINT64.
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
